#ifndef DESIGN_VERIFICATION_H
#define DESIGN_VERIFICATION_H

#define KINETIS_FAKE_SIM                  1
#define MCU_PLATFORM_STM32                  0

#define DESIGN_VERIFICATION_AK8975                  1
#define DESIGN_VERIFICATION_AT24CXX				    1
#define DESIGN_VERIFICATION_BASICTIMER				1
#define DESIGN_VERIFICATION_CHINESE				    1
#define DESIGN_VERIFICATION_CRC					    1
#define DESIGN_VERIFICATION_DELAY					1
#define DESIGN_VERIFICATION_FATFS					1
// #define DESIGN_VERIFICATION_FSM					    1
#define DESIGN_VERIFICATION_GENERAL				    1
#define DESIGN_VERIFICATION_BUTTON					1
#define DESIGN_VERIFICATION_LED						1
#define DESIGN_VERIFICATION_RS485					1
#define DESIGN_VERIFICATION_RTC						1
#define DESIGN_VERIFICATION_RTCTASK					1
#define DESIGN_VERIFICATION_SEIRALPORT				1
#define DESIGN_VERIFICATION_SWITCH					1
#define DESIGN_VERIFICATION_TIMEOUT					1
#define DESIGN_VERIFICATION_TIMTASK					1
#define DESIGN_VERIFICATION_TOUCHSCREEN				1
#define DESIGN_VERIFICATION_DS3231					1
#define DESIGN_VERIFICATION_GT9271					1
#define DESIGN_VERIFICATION_HC_05					1
#define DESIGN_VERIFICATION_HMC5883L				1
#define DESIGN_VERIFICATION_HYDROLOGY				1
#define DESIGN_VERIFICATION_ICM20602				1
#define DESIGN_VERIFICATION_IIC						1
#define DESIGN_VERIFICATION_MAX30205				1
#define DESIGN_VERIFICATION_MEMORY					1
#define DESIGN_VERIFICATION_RNG					    1
#define DESIGN_VERIFICATION_MPU6050					1
#define DESIGN_VERIFICATION_MT29F4G08				1
#define DESIGN_VERIFICATION_MY9221					1
#define DESIGN_VERIFICATION_NBIOT					1
#define DESIGN_VERIFICATION_OLED					1
#define DESIGN_VERIFICATION_RAK477					1
#define DESIGN_VERIFICATION_SHT20					1
#define DESIGN_VERIFICATION_SPL06					1
#define DESIGN_VERIFICATION_SSD1306					1
#define DESIGN_VERIFICATION_TLC5971					1
#define DESIGN_VERIFICATION_W25QXXX					1
#define DESIGN_VERIFICATION_XMODEM					1

#endif /* DESIGN_VERIFICATION_H */