#ifndef  _HYDROLOGYCOMMAND_H_
#define  _HYDROLOGYCOMMAND_H_

#define       HYDROLOGY_RTUTYPE_LEN                     1

#define       HYDROLOGY_CENTER_LEN                      4

#define       HYDROLOGY_REMOTE_LEN                      5

#define       HYDROLOGY_PASSWORD_LEN                    2

#define       HYDROLOGY_CENTER_IP_LEN                   10
#define       HYDROLOGY_BACKUP_IP_LEN                   10

#define       HYDROLOGY_WORK_MODE_LEN                   1

#define       HYDROLOGY_ELEMENT_SELECT_LEN              8
#define       HYDROLOGY_REPEATER_STATION_LEN            12
#define       HYDROLOGY_DEVICE_ID_LEN                   12

#define       HYDROLOGY_TIMER_INTERVAL_LEN              1
#define       HYDROLOGY_ADD_INTERVAL_LEN                1
#define       HYDROLOGY_RAINFALL_BEGIN_TIME_LEN         1
#define       HYDROLOGY_SAMPLE_INTERVAL_LEN             2
#define       HYDROLOGY_WATERLEVEL_STORE_INTERVAL_LEN   1
#define       HYDROLOGY_RAINFALL_RESOLUTION_LEN         1
#define       HYDROLOGY_WATERLEVEL_RESOLUTION_LEN       1
#define       HYDROLOGY_RAINFALL_ADD_THRESHOLD_LEN      1
#define       HYDROLOGY_WATERLEVEL_BASICVALUE1_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE2_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE3_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE4_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE5_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE6_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE7_LEN      4
#define       HYDROLOGY_WATERLEVEL_BASICVALUE8_LEN      4
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE1_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE2_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE3_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE4_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE5_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE6_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE7_LEN    3
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE8_LEN    3
#define       HYDROLOGY_ADD_WATERLEVEL1_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL2_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL3_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL4_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL5_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL6_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL7_LEN             2
#define       HYDROLOGY_ADD_WATERLEVEL8_LEN             2
#define       HYDROLOGY_ADD_ABOVE_THRESHOLD_LEN         2
#define       HYDROLOGY_ADD_BELOW_THRESHOLD_LEN         2

#define       HYDROLOGY_SOFTWARE_VERSION_LEN            17
#define       HYDROLOGY_STATUS_ALARM_INFO_LEN           4

#define       HYDROLOGY_OBSERVATION_TIME_LEN            5

#define       HYDROLOGY_ISR_COUNT_LEN                   5

#define       HYDROLOGY_ANALOG_LEN                      4

#define       HYDROLOGY_PULSE_LEN                       4

#define       HYDROLOGY_SWITCH_LEN                      4

#define       HYDROLOGY_RS485_COUNT_LEN                 1

#define       HYDROLOGY_RS485_LEN                       5

#define       EVENPERIODELEMENT_SAMPLETIME_LEN          5
#define       TIMESTEP_LEN                              3
#define       EVENPERIODELEMENT_LEN                     4 * 12

#define       ARTIFICIAL_NUMNER_LEN                     128
#define       ARTIFICIAL_NUMNER_SIZE_LEN                1

#define       HYDROLOGY_PUMP_LEN                        2
#define       HYDROLOGY_VALVE_LEN                       2
#define       HYDROLOGY_GATE_LEN                        18
#define       HYDROLOGY_PUMP_SIZE_LEN                   1
#define       HYDROLOGY_VALVE_SIZE_LEN                  1
#define       HYDROLOGY_GATE_SIZE_LEN                   1
#define       HYDROLOGY_WATERSETTING_LEN                1
#define       HYDROLOGY_RECORD_LEN                      2 * 32

#define       HYDROLOGY_PICTURE_SIZE_LEN                2
#define       HYDROLOGY_PICTURE_SINGLE_LEN              200
#define       HYDROLOGY_PICTURE_LEN                     4096

/*The following program is modified by the user according to the hardware device, otherwise the driver cannot run.*/
#define       HYDROLOGY_CONFIG_ADDR                     0x0
/*The above procedure is modified by the user according to the hardware device, otherwise the driver cannot run.*/

#define       HYDROLOGY_RTUTYPE                         HYDROLOGY_CONFIG_ADDR + 0

#define       HYDROLOGY_CENTER_ADDR                     HYDROLOGY_RTUTYPE + HYDROLOGY_RTUTYPE_LEN

#define       HYDROLOGY_REMOTE_ADDR                     HYDROLOGY_CENTER_ADDR + HYDROLOGY_CENTER_LEN

#define       HYDROLOGY_PASSWORD_ADDR                   HYDROLOGY_REMOTE_ADDR + HYDROLOGY_REMOTE_LEN

#define       HYDROLOGY_CENTER1_IP                      HYDROLOGY_PASSWORD_ADDR + HYDROLOGY_PASSWORD_LEN
#define       HYDROLOGY_BACKUP1_IP                      HYDROLOGY_CENTER1_IP + HYDROLOGY_CENTER_IP_LEN
#define       HYDROLOGY_CENTER2_IP                      HYDROLOGY_BACKUP1_IP + HYDROLOGY_BACKUP_IP_LEN
#define       HYDROLOGY_BACKUP2_IP                      HYDROLOGY_CENTER2_IP + HYDROLOGY_CENTER_IP_LEN
#define       HYDROLOGY_CENTER3_IP                      HYDROLOGY_BACKUP2_IP + HYDROLOGY_BACKUP_IP_LEN
#define       HYDROLOGY_BACKUP3_IP                      HYDROLOGY_CENTER3_IP + HYDROLOGY_CENTER_IP_LEN
#define       HYDROLOGY_CENTER4_IP                      HYDROLOGY_BACKUP3_IP + HYDROLOGY_BACKUP_IP_LEN
#define       HYDROLOGY_BACKUP4_IP                      HYDROLOGY_CENTER4_IP + HYDROLOGY_CENTER_IP_LEN

#define       HYDROLOGY_WORK_MODE                       HYDROLOGY_BACKUP4_IP + HYDROLOGY_BACKUP_IP_LEN

#define       HYDROLOGY_ELEMENT_SELECT                  HYDROLOGY_WORK_MODE + HYDROLOGY_WORK_MODE_LEN
#define       HYDROLOGY_REPEATER_STATION                HYDROLOGY_ELEMENT_SELECT + HYDROLOGY_ELEMENT_SELECT_LEN
#define       HYDROLOGY_DEVICE_ID                       HYDROLOGY_REPEATER_STATION + HYDROLOGY_REPEATER_STATION_LEN

#define       HYDROLOGY_TIMER_INTERVAL                  HYDROLOGY_DEVICE_ID + HYDROLOGY_DEVICE_ID_LEN
#define       HYDROLOGY_ADD_INTERVAL                    HYDROLOGY_TIMER_INTERVAL + HYDROLOGY_TIMER_INTERVAL_LEN
#define       HYDROLOGY_RAINFALL_BEGIN_TIME             HYDROLOGY_ADD_INTERVAL + HYDROLOGY_ADD_INTERVAL_LEN
#define       HYDROLOGY_SAMPLE_INTERVAL                 HYDROLOGY_RAINFALL_BEGIN_TIME + HYDROLOGY_RAINFALL_BEGIN_TIME_LEN
#define       HYDROLOGY_WATERLEVEL_STORE_INTERVAL       HYDROLOGY_SAMPLE_INTERVAL + HYDROLOGY_SAMPLE_INTERVAL_LEN
#define       HYDROLOGY_RAINFALL_RESOLUTION             HYDROLOGY_WATERLEVEL_STORE_INTERVAL + HYDROLOGY_WATERLEVEL_STORE_INTERVAL_LEN
#define       HYDROLOGY_WATERLEVEL_RESOLUTION           HYDROLOGY_RAINFALL_RESOLUTION + HYDROLOGY_RAINFALL_RESOLUTION_LEN
#define       HYDROLOGY_RAINFALL_ADD_THRESHOLD          HYDROLOGY_WATERLEVEL_RESOLUTION + HYDROLOGY_WATERLEVEL_RESOLUTION_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE1          HYDROLOGY_RAINFALL_ADD_THRESHOLD + HYDROLOGY_RAINFALL_ADD_THRESHOLD_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE2          HYDROLOGY_WATERLEVEL_BASICVALUE1 + HYDROLOGY_WATERLEVEL_BASICVALUE1_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE3          HYDROLOGY_WATERLEVEL_BASICVALUE2 + HYDROLOGY_WATERLEVEL_BASICVALUE2_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE4          HYDROLOGY_WATERLEVEL_BASICVALUE3 + HYDROLOGY_WATERLEVEL_BASICVALUE3_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE5          HYDROLOGY_WATERLEVEL_BASICVALUE4 + HYDROLOGY_WATERLEVEL_BASICVALUE4_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE6          HYDROLOGY_WATERLEVEL_BASICVALUE5 + HYDROLOGY_WATERLEVEL_BASICVALUE5_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE7          HYDROLOGY_WATERLEVEL_BASICVALUE6 + HYDROLOGY_WATERLEVEL_BASICVALUE6_LEN
#define       HYDROLOGY_WATERLEVEL_BASICVALUE8          HYDROLOGY_WATERLEVEL_BASICVALUE7 + HYDROLOGY_WATERLEVEL_BASICVALUE7_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE1        HYDROLOGY_WATERLEVEL_BASICVALUE8 + HYDROLOGY_WATERLEVEL_BASICVALUE8_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE2        HYDROLOGY_WATERLEVEL_CORRECTVALUE1 + HYDROLOGY_WATERLEVEL_CORRECTVALUE1_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE3        HYDROLOGY_WATERLEVEL_CORRECTVALUE2 + HYDROLOGY_WATERLEVEL_CORRECTVALUE2_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE4        HYDROLOGY_WATERLEVEL_CORRECTVALUE3 + HYDROLOGY_WATERLEVEL_CORRECTVALUE3_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE5        HYDROLOGY_WATERLEVEL_CORRECTVALUE4 + HYDROLOGY_WATERLEVEL_CORRECTVALUE4_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE6        HYDROLOGY_WATERLEVEL_CORRECTVALUE5 + HYDROLOGY_WATERLEVEL_CORRECTVALUE5_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE7        HYDROLOGY_WATERLEVEL_CORRECTVALUE6 + HYDROLOGY_WATERLEVEL_CORRECTVALUE6_LEN
#define       HYDROLOGY_WATERLEVEL_CORRECTVALUE8        HYDROLOGY_WATERLEVEL_CORRECTVALUE7 + HYDROLOGY_WATERLEVEL_CORRECTVALUE7_LEN
#define       HYDROLOGY_ADD_WATERLEVEL1                 HYDROLOGY_WATERLEVEL_CORRECTVALUE8 + HYDROLOGY_WATERLEVEL_CORRECTVALUE8_LEN
#define       HYDROLOGY_ADD_WATERLEVEL2                 HYDROLOGY_ADD_WATERLEVEL1 + HYDROLOGY_ADD_WATERLEVEL1_LEN
#define       HYDROLOGY_ADD_WATERLEVEL3                 HYDROLOGY_ADD_WATERLEVEL2 + HYDROLOGY_ADD_WATERLEVEL2_LEN
#define       HYDROLOGY_ADD_WATERLEVEL4                 HYDROLOGY_ADD_WATERLEVEL3 + HYDROLOGY_ADD_WATERLEVEL3_LEN
#define       HYDROLOGY_ADD_WATERLEVEL5                 HYDROLOGY_ADD_WATERLEVEL4 + HYDROLOGY_ADD_WATERLEVEL4_LEN
#define       HYDROLOGY_ADD_WATERLEVEL6                 HYDROLOGY_ADD_WATERLEVEL5 + HYDROLOGY_ADD_WATERLEVEL5_LEN
#define       HYDROLOGY_ADD_WATERLEVEL7                 HYDROLOGY_ADD_WATERLEVEL6 + HYDROLOGY_ADD_WATERLEVEL6_LEN
#define       HYDROLOGY_ADD_WATERLEVEL8                 HYDROLOGY_ADD_WATERLEVEL7 + HYDROLOGY_ADD_WATERLEVEL7_LEN
#define       HYDROLOGY_ADD_ABOVE_THRESHOLD             HYDROLOGY_ADD_WATERLEVEL8 + HYDROLOGY_ADD_WATERLEVEL8_LEN
#define       HYDROLOGY_ADD_BELOW_THRESHOLD             HYDROLOGY_ADD_ABOVE_THRESHOLD + HYDROLOGY_ADD_ABOVE_THRESHOLD_LEN

#define       HYDROLOGY_SOFTWARE_VERSION                HYDROLOGY_ADD_BELOW_THRESHOLD + HYDROLOGY_ADD_BELOW_THRESHOLD_LEN
#define       HYDROLOGY_STATUS_ALARM_INFO               HYDROLOGY_SOFTWARE_VERSION + HYDROLOGY_SOFTWARE_VERSION_LEN

#define       HYDROLOGY_ISR_COUNT1                      HYDROLOGY_STATUS_ALARM_INFO + HYDROLOGY_STATUS_ALARM_INFO_LEN
#define       HYDROLOGY_ISR_COUNT2                      HYDROLOGY_ISR_COUNT1 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ISR_COUNT3                      HYDROLOGY_ISR_COUNT2 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ISR_COUNT4                      HYDROLOGY_ISR_COUNT3 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ISR_COUNT5                      HYDROLOGY_ISR_COUNT4 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ISR_COUNT6                      HYDROLOGY_ISR_COUNT5 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ISR_COUNT7                      HYDROLOGY_ISR_COUNT6 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ISR_COUNT8                      HYDROLOGY_ISR_COUNT7 + HYDROLOGY_ISR_COUNT_LEN

#define       HYDROLOGY_ANALOG1                         HYDROLOGY_ISR_COUNT8 + HYDROLOGY_ISR_COUNT_LEN
#define       HYDROLOGY_ANALOG2                         HYDROLOGY_ANALOG1 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG3                         HYDROLOGY_ANALOG2 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG4                         HYDROLOGY_ANALOG3 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG5                         HYDROLOGY_ANALOG4 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG6                         HYDROLOGY_ANALOG5 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG7                         HYDROLOGY_ANALOG6 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG8                         HYDROLOGY_ANALOG7 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG9                         HYDROLOGY_ANALOG8 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG10                        HYDROLOGY_ANALOG9 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG11                        HYDROLOGY_ANALOG10 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG12                        HYDROLOGY_ANALOG11 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG13                        HYDROLOGY_ANALOG12 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG14                        HYDROLOGY_ANALOG13 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG15                        HYDROLOGY_ANALOG14 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG16                        HYDROLOGY_ANALOG15 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG17                        HYDROLOGY_ANALOG16 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG18                        HYDROLOGY_ANALOG17 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG19                        HYDROLOGY_ANALOG18 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG20                        HYDROLOGY_ANALOG19 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG21                        HYDROLOGY_ANALOG20 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG22                        HYDROLOGY_ANALOG21 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG23                        HYDROLOGY_ANALOG22 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG24                        HYDROLOGY_ANALOG23 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG25                        HYDROLOGY_ANALOG24 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG26                        HYDROLOGY_ANALOG25 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG27                        HYDROLOGY_ANALOG26 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG28                        HYDROLOGY_ANALOG27 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG29                        HYDROLOGY_ANALOG28 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG30                        HYDROLOGY_ANALOG29 + HYDROLOGY_ANALOG_LEN

#define       HYDROLOGY_ANALOG1_OBSERVATION_TIME        HYDROLOGY_ANALOG30 + HYDROLOGY_ANALOG_LEN
#define       HYDROLOGY_ANALOG2_OBSERVATION_TIME        HYDROLOGY_ANALOG1_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG3_OBSERVATION_TIME        HYDROLOGY_ANALOG2_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG4_OBSERVATION_TIME        HYDROLOGY_ANALOG3_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG5_OBSERVATION_TIME        HYDROLOGY_ANALOG4_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG6_OBSERVATION_TIME        HYDROLOGY_ANALOG5_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG7_OBSERVATION_TIME        HYDROLOGY_ANALOG6_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG8_OBSERVATION_TIME        HYDROLOGY_ANALOG7_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG9_OBSERVATION_TIME        HYDROLOGY_ANALOG8_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_ANALOG10_OBSERVATION_TIME       HYDROLOGY_ANALOG9_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN

#define       HYDROLOGY_PULSE1                          HYDROLOGY_ANALOG10_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE2                          HYDROLOGY_PULSE1 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE3                          HYDROLOGY_PULSE2 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE4                          HYDROLOGY_PULSE3 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE5                          HYDROLOGY_PULSE4 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE6                          HYDROLOGY_PULSE5 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE7                          HYDROLOGY_PULSE6 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE8                          HYDROLOGY_PULSE7 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE9                          HYDROLOGY_PULSE8 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE10                         HYDROLOGY_PULSE9 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE11                         HYDROLOGY_PULSE10 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE12                         HYDROLOGY_PULSE11 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE13                         HYDROLOGY_PULSE12 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE14                         HYDROLOGY_PULSE13 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE15                         HYDROLOGY_PULSE14 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE16                         HYDROLOGY_PULSE15 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE17                         HYDROLOGY_PULSE16 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE18                         HYDROLOGY_PULSE17 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE19                         HYDROLOGY_PULSE18 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE20                         HYDROLOGY_PULSE19 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE21                         HYDROLOGY_PULSE20 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE22                         HYDROLOGY_PULSE21 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE23                         HYDROLOGY_PULSE22 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE24                         HYDROLOGY_PULSE23 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE25                         HYDROLOGY_PULSE24 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE26                         HYDROLOGY_PULSE25 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE27                         HYDROLOGY_PULSE26 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE28                         HYDROLOGY_PULSE27 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE29                         HYDROLOGY_PULSE28 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE30                         HYDROLOGY_PULSE29 + HYDROLOGY_PULSE_LEN

#define       HYDROLOGY_PULSE1_OBSERVATION_TIME         HYDROLOGY_PULSE30 + HYDROLOGY_PULSE_LEN
#define       HYDROLOGY_PULSE2_OBSERVATION_TIME         HYDROLOGY_PULSE1_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE3_OBSERVATION_TIME         HYDROLOGY_PULSE2_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE4_OBSERVATION_TIME         HYDROLOGY_PULSE3_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE5_OBSERVATION_TIME         HYDROLOGY_PULSE4_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE6_OBSERVATION_TIME         HYDROLOGY_PULSE5_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE7_OBSERVATION_TIME         HYDROLOGY_PULSE6_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE8_OBSERVATION_TIME         HYDROLOGY_PULSE7_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE9_OBSERVATION_TIME         HYDROLOGY_PULSE8_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_PULSE10_OBSERVATION_TIME        HYDROLOGY_PULSE9_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN

#define       HYDROLOGY_SWITCH1                         HYDROLOGY_PULSE10_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN

#define       HYDROLOGY_SWITCH1_OBSERVATION_TIME        HYDROLOGY_SWITCH1 + HYDROLOGY_SWITCH_LEN

#define       HYDROLOGY_RS485_COUNT1                    HYDROLOGY_SWITCH1_OBSERVATION_TIME + HYDROLOGY_OBSERVATION_TIME_LEN
#define       HYDROLOGY_RS485_COUNT2                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT3                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT4                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT5                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT6                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT7                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT8                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT9                    HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS485_COUNT10                   HYDROLOGY_RS485_COUNT1 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS4851                          HYDROLOGY_RS485_COUNT10 + HYDROLOGY_RS485_COUNT_LEN
#define       HYDROLOGY_RS4852                          HYDROLOGY_RS4851 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4853                          HYDROLOGY_RS4852 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4854                          HYDROLOGY_RS4853 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4855                          HYDROLOGY_RS4854 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4856                          HYDROLOGY_RS4855 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4857                          HYDROLOGY_RS4856 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4858                          HYDROLOGY_RS4857 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS4859                          HYDROLOGY_RS4858 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48510                         HYDROLOGY_RS4859 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48511                         HYDROLOGY_RS48510 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48512                         HYDROLOGY_RS48511 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48513                         HYDROLOGY_RS48512 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48514                         HYDROLOGY_RS48513 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48515                         HYDROLOGY_RS48514 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48516                         HYDROLOGY_RS48515 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48517                         HYDROLOGY_RS48516 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48518                         HYDROLOGY_RS48517 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48519                         HYDROLOGY_RS48518 + HYDROLOGY_RS485_LEN
#define       HYDROLOGY_RS48520                         HYDROLOGY_RS48519 + HYDROLOGY_RS485_LEN

#define       EVENPERIODELEMENT_SAMPLETIME              HYDROLOGY_RS48520 + HYDROLOGY_RS485_LEN
#define       TIMESTEP                                  EVENPERIODELEMENT_SAMPLETIME + EVENPERIODELEMENT_SAMPLETIME_LEN
#define       EVENPERIODELEMENT                         TIMESTEP + TIMESTEP_LEN

#define       ARTIFICIAL_NUMNER                         EVENPERIODELEMENT + EVENPERIODELEMENT_LEN
#define       ARTIFICIAL_NUMNER_SIZE                    ARTIFICIAL_NUMNER + ARTIFICIAL_NUMNER_LEN

#define       HYDROLOGY_PUMP                            ARTIFICIAL_NUMNER_SIZE + ARTIFICIAL_NUMNER_SIZE_LEN
#define       HYDROLOGY_VALVE                           HYDROLOGY_PUMP + HYDROLOGY_PUMP_LEN
#define       HYDROLOGY_GATE                            HYDROLOGY_VALVE + HYDROLOGY_VALVE_LEN
#define       HYDROLOGY_WATERSETTING                    HYDROLOGY_GATE + HYDROLOGY_GATE_LEN
#define       HYDROLOGY_RECORD                          HYDROLOGY_WATERSETTING + HYDROLOGY_WATERSETTING_LEN

#define       HYDROLOGY_PICTURE_SIZE                    HYDROLOGY_RECORD + HYDROLOGY_RECORD_LEN
#define       HYDROLOGY_PICTURE                         HYDROLOGY_PICTURE_SIZE + HYDROLOGY_PICTURE_SIZE_LEN

#define       HYDROLOGY_END                             HYDROLOGY_PICTURE + HYDROLOGY_PICTURE_LEN


int HydrologyRecord(int index);

int hydrologyCommand(int type);

void RS485_Dir(char inout);

int hydrologyInitializeSolidStorage(void);

int Hydrology_Reset(void);

void Hydrology_ReadRS485(char *value,int index);

int HydrologyReadSuiteElement(int type,char* guide,char* value);



#endif /* _HYDROLOGYCOMMAND_H_ */
