// SPDX-License-Identifier: GPL-2.0
/*
 *  linux/lib/ctype.c
 *
 *  Copyright (C) 1991, 1992  Linus Torvalds
 */

#include <generated/deconfig.h> 
#include <linux/ctype.h>
#include <linux/compiler.h>
#include <linux/export.h>

const unsigned char _ctype[] = {
_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,				/* 0-7 */
_CTYPE_C,_CTYPE_C|_CTYPE_S,_CTYPE_C|_CTYPE_S,_CTYPE_C|_CTYPE_S,_CTYPE_C|_CTYPE_S,_CTYPE_C|_CTYPE_S,_CTYPE_C,_CTYPE_C,			/* 8-15 */
_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,				/* 16-23 */
_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,_CTYPE_C,				/* 24-31 */
_CTYPE_S|_CTYPE_SP,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,				/* 32-39 */
_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,				/* 40-47 */
_CTYPE_D,_CTYPE_D,_CTYPE_D,_CTYPE_D,_CTYPE_D,_CTYPE_D,_CTYPE_D,_CTYPE_D,				/* 48-55 */
_CTYPE_D,_CTYPE_D,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,				/* 56-63 */
_CTYPE_P,_CTYPE_U|_CTYPE_X,_CTYPE_U|_CTYPE_X,_CTYPE_U|_CTYPE_X,_CTYPE_U|_CTYPE_X,_CTYPE_U|_CTYPE_X,_CTYPE_U|_CTYPE_X,_CTYPE_U,		/* 64-71 */
_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,				/* 72-79 */
_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,				/* 80-87 */
_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,				/* 88-95 */
_CTYPE_P,_CTYPE_L|_CTYPE_X,_CTYPE_L|_CTYPE_X,_CTYPE_L|_CTYPE_X,_CTYPE_L|_CTYPE_X,_CTYPE_L|_CTYPE_X,_CTYPE_L|_CTYPE_X,_CTYPE_L,		/* 96-103 */
_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,				/* 104-111 */
_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,				/* 112-119 */
_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_C,				/* 120-127 */
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,			/* 128-143 */
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,			/* 144-159 */
_CTYPE_S|_CTYPE_SP,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,	/* 160-175 */
_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,_CTYPE_P,	/* 176-191 */
_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,	/* 192-207 */
_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_P,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_U,_CTYPE_L,	/* 208-223 */
_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,	/* 224-239 */
_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_P,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L,_CTYPE_L};	/* 240-255 */

EXPORT_SYMBOL(_ctype);
